branch-defaults:
  default:
    environment: udacity-fullsnack-js-4
global:
  application_name: udagram-api
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  workspace_type: Application
